# Generated by Django 4.1 on 2022-08-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslatter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('published', 'Published')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
